### PR TITLE
Update input list in action.yml

### PR DESCRIPTION
**Pull request by teodragovic**
Including descriptions and default values for `pattern` and `exclude`.

### CODE REVIEW

**Comment by swissspidy** [comment]
@developit Would be great if you could take a look at this one.

Currently getting the following warning when using `pattern`:

```
##[warning]Unexpected input 'pattern', valid inputs are ['repo-token', 'build-script', 'compression', 'show-total', 'collapse-unchanged', 'omit-unchanged', 'strip-hash', 'use-check']
```

**Comment by developit** [comment]
I'll try to get this released shortly.

**Comment by brandonweiss** [comment]
@developit 🙏 😬

**Comment by developit** [comment]
Apologies for being slow to release this - I've run into it three times now and keep failing to get around to it!

**Comment by developit** [comment]
Released as v2 (v2.0.1).

**Pull request merged**
