### PR TITLE
Add pnpm support

### PR DESCRIPTION
**Pull request by apazzolini**
Closes https://github.com/preactjs/compressed-size-action/issues/52

### CODE REVIEW

**Comment by flybayer** [comment]
@developit have you had a chance to look at this?

**Comment by sarayourfriend** [comment]
We could use this over at https://github.com/WordPress/Gutenberg.

Anything I can do to help prioritize reviewing and merging this PR? 🙂

**Comment by developit** [comment]
Apologies for the wait. This looks fine to me, I'll get it merged Monday.

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Published as [2.4.0](https://github.com/preactjs/compressed-size-action/releases/tag/2.4.0) (and `@v2`).

**Pull request merged**
