### PR TITLE
Remove bot check for existing comments

### PR DESCRIPTION
**Pull request by flugg**
Fixes https://github.com/preactjs/compressed-size-action/issues/79

### CODE REVIEW

**Review by developit — APPROVED** [review]
I think this should be fine.

**Comment by flugg** [comment]
Excellent! We're eagerly waiting for this update, when do you think it could be released @developit ?

**Comment by flugg** [comment]
Any updates @developit ? 😄

**Comment by datagutt** [comment]
Hey @developit,
I hope everything is well. I am also experiencing this issue.
Is this a suitable solution that can be merged, or should it be solved differently? I am happy to discuss other options to solve this.

**Comment by rschristian** [comment]
Sorry for the close & reopen, needed to give the CI a little kick

**Review by rschristian — APPROVED** [review]

**Pull request merged**
